# Generated by Django 5.0.6 on 2024-06-26 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=50, unique=True)),
                ('bus_manufacture', models.CharField(max_length=200)),
                ('bus_reg', models.CharField(max_length=50)),
                ('bus_owner', models.CharField(max_length=50)),
                ('bus_owner_contact', models.CharField(max_length=50)),
                ('bus_owner_email', models.EmailField(max_length=254)),
                ('bus_driver', models.CharField(max_length=50)),
                ('bus_driver_contact', models.CharField(max_length=50)),
                ('bus_driver_email', models.EmailField(max_length=254)),
                ('bus_conductor', models.CharField(max_length=50)),
                ('bus_conductor_contact', models.CharField(max_length=50)),
                ('bus_conductor_email', models.EmailField(max_length=254)),
                ('date_purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('registered_date', models.DateTimeField(auto_now=True)),
                ('bus_insurance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50, unique=True)),
                ('route_name', models.CharField(max_length=50, unique=True)),
                ('route_destination1', models.CharField(max_length=50, unique=True)),
                ('route_destination2', models.CharField(max_length=50, unique=True)),
                ('route_destination3', models.CharField(max_length=50, unique=True)),
                ('route_destination4', models.CharField(max_length=50, unique=True)),
                ('route_fare', models.CharField(max_length=50, unique=True)),
                ('route_bus1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route1', to='myapp.bus')),
                ('route_bus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route2', to='myapp.bus')),
                ('route_bus3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route3', to='myapp.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_route',
            field=models.ManyToManyField(related_name='buses', to='myapp.route'),
        ),
    ]
