# Generated by Django 5.0.6 on 2024-07-02 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_bus_conductor_email_bus_bus_conductor_identification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sacco_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conductor_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_date', models.DateField()),
                ('last_tyre_replacement', models.DateField()),
                ('next_inspection_date', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='myapp.bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.bus')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
