# Generated by Django 5.0.6 on 2024-07-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_booking_booking_cancel_remove_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sacco_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conductor_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_date', models.DateField()),
                ('last_tyre_replacement', models.DateField()),
                ('next_inspection_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_route',
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_conductor_identification',
            field=models.IntegerField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_driver_identification',
            field=models.IntegerField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_owner_identification',
            field=models.IntegerField(max_length=254),
        ),
    ]
