# Generated by Django 5.0.6 on 2024-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_expenditure_remove_bus_bus_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_cancellation',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_payment',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=255, null=True),
        ),
    ]
