# Generated by Django 5.0.6 on 2024-07-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booking_booking_cancellation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_cancellation',
            new_name='booking_confirmation',
        ),
    ]
