# Generated by Django 5.0.7 on 2024-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
